### ISSUE TITLE
problem using it with switch

### ISSUE THREAD

**Issue by rsingh106** [spencerccf/app_settings#1]
I tried to implement it on a switch although it works but it always goes into a loop where it says the value is always false.

 D/ViewRootImpl@6fe231b[MainActivity](10390): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x3 surface={valid=true 511763673088} changed=false

**Comment by spencerccf** [comment]
Hi @rsingh106, could you provide me with an example of you implementation and I'll get the needed updates in place.

**Comment by spencerccf** [comment]
Closing this issue until an example is provided.  Please reopen issue when ready with an example.
