### ISSUE TITLE
How to open general settings in iOS?

### ISSUE THREAD

**Issue by IRTonyCHAN** [spencerccf/app_settings#107]
Is there any method allow to open general setting page?
Currently all method on iOS is open app setting page.

Since I saw this app can go to general setting page instead of app setting page.
https://apps.apple.com/app/%E7%B1%B3%E5%AE%B6/id957323480

**Comment by OGmetamonkey** [comment]
I would also highly appreciate help doing this. Preferably for versions 4.0.4 and below.
