### ISSUE TITLE
OpenBluetoothSettings takes me to "Connected devices" Page

### ISSUE THREAD

**Issue by GaelleJoubert** [spencerccf/app_settings#109]
I'm using the "AppSettings.openBluetoothSettings();" function, and instead of taking me to the bluetooth page where I can enable or disable the bluetooth, it takes me to the "Connected Devices" page.

From here if I want to enable the bluetooth, I need to clic on "Connexion Preferences", and then "Bluetooth".

By trying everything, I realised that "AppSettings.openNFCSettings();" takes me to that "Connexion Preferences" page.

My phone is an Android, V11, with the update from the 1st of August 2021.

Is it possible to update the path, and actually "openBluetoothSettings" point to the bluetooth page ? thanks !

**Comment by sonelektrikci** [comment]
I'm getting the same issue. openBluetoothSettings() does not direct to the bluetooth page.

**Comment by d-wolf** [comment]
@plinkos The issue is still present. Tested on my Android 10 and 12 devices. For both the openBluetoothSettings command opens the connected devices page.

**Comment by plinkos** [comment]
I will take a look and see what I can adjust for those OS versions. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BellRampion** [comment]
This is also present on Android version 9.

**Comment by plinkos** [comment]
I’ll take a look and see what’s going on and get a fix pushed up. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
