### ISSUE TITLE
iOS 15 - AppSettings.openLocationSettings() goes to wrong setting screen

### ISSUE THREAD

**Issue by DuncanKelbie** [spencerccf/app_settings#110]
On iOS 15, AppSettings.openLocationSettings() opens the app settings screen instead of the location settings screen. On previous versions of iOS, this would open the location settings screen.

**Comment by Artur-Wisniewski** [comment]
On iOS 15 I have this behavior on every `AppSettings.open...Settings()`

**Comment by AliRezaBeitari** [comment]
Me too. None of the methods work and only navigate me to the  general app settings screen.

**Comment by plinkos** [comment]
This is normal behavior on iOS ... Apple doesn't allow any app to open any specific screen.  The App Settings screen should provide what settings that your app has implemented first.  If you app has implemented say location settings via prompting the user for location... that will then appear in app settings screen.  Android will allow you to open individual screens.
