### ISSUE TITLE
Migrate maven repository from JCenter to MavenCentral

### ISSUE THREAD

**Issue by temarez** [spencerccf/app_settings#119]
[jcenter.bintray.com](https://jcenter.bintray.com/) will not be available since February 1st, 2022. See more info at [JCenter and Bintray is shutting down, what to do?](https://testfairy.com/blog/jcenter-and-bintray-is-shutting-down-what-to-do/)
This may cause inability of the project using `app_settings` to be built on the clean environment.

Migration can be done by replacing `jcenter()` to `mavenCentral()` in these gradle files:
[android/build.gradle](https://github.com/spencerccf/app_settings/blob/master/android/build.gradle)
[example/android/build.gradle](https://github.com/spencerccf/app_settings/blob/master/example/android/build.gradle)

**Comment by plinkos** [comment]
Done... get latest version from pub.dev 4.1.4
