### ISSUE TITLE
Not working on Flutter master branch

### ISSUE THREAD

**Issue by TheJulianJES** [spencerccf/app_settings#124]
The latest master branch of ``app_settings`` doesn't seem to work with the latest master branch of Flutter.

Compilation error:
```
flutter/.pub-cache/git/app_settings-bef4a699ae37c1ed19e3590ed9ff9e87274de3c4/android/src/main/kotlin/com/example/appsettings/AppSettingsPlugin.kt: (44, 25): Type mismatch: inferred type is Activity? but Activity was expected
```
Issue:
https://github.com/spencerccf/app_settings/blob/bef4a699ae37c1ed19e3590ed9ff9e87274de3c4/android/src/main/kotlin/com/example/appsettings/AppSettingsPlugin.kt#L44

**Comment by plinkos** [comment]
Try …

flutter pub cache repair


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheJulianJES** [comment]
That doesn't seem to work for me.

Changing the line to the following does seem to work (although it's less than ideal).
```kotlin
this.activity = registrar.activity()!!
```
I'm not sure what changed on Flutter's side that would cause this though.

**Comment by TheJulianJES** [comment]
Might have been a bug in Flutter. Updated to the latest master branch and I think it's working without the changes now.
