### ISSUE TITLE
AppSettingsPlugin.kt: (44, 25): Type mismatch: inferred type is Activity? but Activity was expected

### ISSUE THREAD

**Issue by JoshanTandukar** [spencerccf/app_settings#125]
AppSettingsPlugin.kt: (44, 25): Type mismatch: inferred type is Activity? but Activity was expected

**Comment by batuhankrbb** [comment]
I get the same error

**Comment by sayem118** [comment]
I have the same issue

**Comment by large** [comment]
Same issue after changing back to "flutter master" channel

**Comment by plinkos** [comment]
Please try latest pub.dev version: 4.1.3
