### ISSUE TITLE
Cannot open any setting from emulator

### ISSUE THREAD

**Issue by aloklearning** [spencerccf/app_settings#13]
I have used the app_settings in my code, and after using it for the implementation in the emulator iOS, it only throws error : 

`#1      AppSettings.openAppSettings (package:app_settings/app_settings.dart:25:14)
<asynchronous suspension>
#2      _HomeContainerState.permission.<anonymous closure>.<anonymous closure> (package:newmonkapp/screens/home_container.dart:39:42)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
#8      PrimaryPointerGestureReco<…>`

I'm using the package right, but now working on the emulator.

**Comment by fayaz07** [comment]
I too experienced the same in emulator

**Comment by spencerccf** [comment]
Thanks for letting me know.  I will investigate.  In the meantime you should be able to use a physical iOS device for testing.

**Comment by fayaz07** [comment]
Thanks @spencerccf

**Comment by spencerccf** [comment]
Updated readme with Tip on use_frameworks! and published a new version: 1.0.6+1.
