### ISSUE TITLE
Xcode archive failed for xcode 13.3 

### ISSUE THREAD

**Issue by alihassan143** [spencerccf/app_settings#130]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
• No issues found!
<img width="923" alt="Screenshot 2022-04-05 at 4 15 18 PM" src="https://user-images.githubusercontent.com/71745182/161742177-d9727044-e2ab-4f2b-b70e-cf857de48d05.png">

**Comment by plinkos** [comment]
I'll upgrade from 13.1 to 13.3 and see If I can reproduce the error you are seeing.

**Comment by kekko7072** [comment]
+1

**Comment by plinkos** [comment]
I have Xcode 13.3 and Flutter 2.2.2 - channel stable.
I'm able to create a sample Flutter project including the app_settings plugin within the pubspec.yaml and implementing a couple of the calls.   Running and debugging in Xcode works fine.  Also, generation of the Archive worked fine as well.  

Are you able to run the app on simulator in Xcode? 
Did you run: pod install inside of the iOS directory to ensure all pods/libs are in Xcode workspace prods project?

**Comment by alihassan143** [comment]
Now i can be able to build archive by creating new flutter project and app archive is successful i think its flutter project ios file issue after all the previous configurations archive build successfull

**Comment by kekko7072** [comment]
I solved without creating a new app just following [this comment](https://stackoverflow.com/a/71623137/13397584) and [this comment about pod problem](https://stackoverflow.com/a/71699463/13397584) I run and I had on terminal
```
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Running pod install...
Running Xcode build...
```
and problem was fixed.
