### ISSUE TITLE
Flutter 3.0 : Execution failed for task ':app_settings:compileDebugKotlin'

### ISSUE THREAD

**Issue by tudor07** [spencerccf/app_settings#141]
After Flutter 3 upgrade the Android build fails

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app_settings:compileDebugKotlin'.
> Compilation error. See log for more details
```

**Comment by plinkos** [comment]
This plugin has not yet been upgraded to Flutter 3.0.  Feel free to create a pull request to upgrade.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vargascarlitos** [comment]
tomorrow I have free and I will send the PR :P

**Comment by rafaelcolladojr** [comment]
@vargascarlitos looking forward to your PR!

**Comment by kaciula** [comment]
Hi. Does anyone have a temporary workaround for using this plugin on Flutter 3?

**Comment by matAlmeida** [comment]
@kaciula I created a PR #142 with the fix, but meanwhile it's reviewed you can install from my repo.

```
 app_settings:
    git:
      url: https://github.com/PurpleBullDev/app_settings.git
```

**Comment by Galti** [comment]
@plinkos This issue can be closed as [the PR](https://github.com/spencerccf/app_settings/pull/142) already merged.
