### ISSUE TITLE
Because myApp depends on app_settings >=4.1.7 which requires SDK version >=2.12.0 <=2.17.1, version solving failed.

### ISSUE THREAD

**Issue by iLoveDocs** [spencerccf/app_settings#143]
Is there a reason why `app_settings` is using 

```
sdk: ">=2.12.0 <=2.17.1"
```

instead of 

```
sdk: ">=2.17.0 <3.0.0"
```

I am unable to use it (unless I downgrade Flutter).

**Comment by plinkos** [comment]
Yes, the SDK is dart and dart does not have 3.0 yet.  Flutter is set to 3.0.1... this is per Google pub.dev.

**Comment by iLoveDocs** [comment]
@plinkos 

Setting 
```
sdk: ">=2.17.0 <3.0.0"
```

doesn't necessarily mean the Dart needs to be on `3.0.0`. It's the standard convention. All it means is we are targeting Dart SDK till the version `3.0.0` (which may not exist and it's totally fine). Correct me if I'm wrong.

**Comment by plinkos** [comment]
Pub.dev rejected that setting with response that there is no Dart 3.0.

**Comment by plinkos** [comment]
Uploading...
The SDK constraint allows Dart 3.0.0, this is not allowed because Dart 3 does not exist.
pub finished with exit code 1

**Comment by plinkos** [comment]
Done... it is now set to  < 3.0.0 ... I must have set it to <= so it would attempt to go up to Dart 3.0 which doesn't exist yet.  Get latest version: 4.1.8

**Comment by iLoveDocs** [comment]
@plinkos Thanks, that worked !
