### ISSUE TITLE
How can I go to General Settings screen in Ios platform ?

### ISSUE THREAD

**Issue by SuYungCheng** [spencerccf/app_settings#146]
I use your github demo code (version 4.1.1) :  `AppSettings.openWIFISettings(); ` can to general settings screen.

But in my project, and use the same code : ` AppSettings.openWIFISettings();`
just always go to app settings?

don't know why?

The document says: 
All options open the current 'app' settings section if there are settings defined. If no current settings are "defined" for the app the iPhone Settings Screen will be displayed.

What does "defined" words mean?
how can I "not" to defined current settings?

Thanks!

**Comment by elmar001** [comment]
I also need that one. But seems like it can only open app settings if there is any app settings - permissions etc.

**Comment by SuYungCheng** [comment]
It's very strange!

I create a native iOS project  and it can open general settings.
But after I use my flutter project and use channel method to call native code. 
It goes to app settings.

Maybe like you said , something in the app settings.

But other app also has that, and it can go general settings.
><

**Comment by SuYungCheng** [comment]
ya, I know it can't access to WIFI settings.

what I want is to open General Settings and don't use the rejecting words  "Prefs:root".

It will be reject by apple.

**Comment by SuYungCheng** [comment]
@plinkos  you mean if I implement the security for WiFi access in info.plist, I will always open App Settings. Right?

**Comment by plinkos** [comment]
Yes, the settings you have permission granted for will appear in app settings screen. 

https://betterprogramming.pub/wifi-permission-changes-for-ios-12-1-iphone-x-and-other-devices-c313e24f90ae

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SuYungCheng** [comment]
Thank you for clearing up my confusion.

After I remove the Entitlements.plist for WiFi access, I can go to general settings.

But also make the other issue:

My app need to get WiFi name to let users know.

So I used the package  "network_info_plus".

When I remove the WiFi access, the WiFi name return null.

How can I both to get WiFi name and access to general settings?

Like some iot app, 
[for example](https://apps.apple.com/tw/app/tuya-smart/id1034649547)

**Comment by plinkos** [comment]
Check this out: https://developer.apple.com/forums/thread/679038

**Comment by SuYungCheng** [comment]
Thank you @plinkos .

You help me a lot.

I'll try it.

Hope it can work.
