### ISSUE TITLE
[IOS] How can I go to General Settings -> Apple Account -> Subscriptions screen?

### ISSUE THREAD

**Issue by adiPumba** [spencerccf/app_settings#147]
Hi,

How can I use this package in order to navigate to General Settings -> Apple Account -> Subscriptions screen?

**Comment by plinkos** [comment]
My be possible... I'm investigating these options:
iOS: https://developer.apple.com/documentation/storekit/appstore/3803198-showmanagesubscriptions
Android: https://developer.android.com/reference/kotlin/android/telephony/SubscriptionManager

**Comment by plinkos** [comment]
StoreKit.AppStore.showManageSubscriptions(in: windowScene) is available to be used but this will only open subscriptions that your user has access to from within your app.  i.e. I believe the subscription would need to be originally initiated by your app bundle.  There is the OLD URL: itms-apps://apps.apple.com/account/subscriptions but this will get your app rejected from Apple.

Would you still like to have StoreKit.AppStore.showManageSubscriptions(in: windowScene) added to the app_settings plugin?
