### ISSUE TITLE
iOS: Unable to open WIFI and Bluetooth settings

### ISSUE THREAD

**Issue by shreyasb07** [spencerccf/app_settings#148]
Using the plugin on iOS/iPadOS devices, I am unable to open the Wifi and Bluetooth settings directly. Instead it opens the devices' Settings page. Shouldn't it take the user directly to the wifi and bluetooth settings?

`AppSettings.openWIFISettings();`
`    AppSettings.openBluetoothSettings();`

**Comment by plinkos** [comment]
iOS only allows opening of an App Settings screen... so permissions must be set correctly and code needs to attempt to access the setting/feature and prompt user initially.  Then that setting will appear in the app settings screen.  This is just the way Apple requires things for iPhone/iPad apps.
