### ISSUE TITLE
needs info about swift requirement

### ISSUE THREAD

**Issue by gkrawiec** [spencerccf/app_settings#15]
Your plugin requires a few changes to the flutter default environment. It needs the swift bridging support and a change in the podfile to support framework. Please add this info and, ideally also instructions, on your install page. Without the changes the plugin does not work on ios. thank you.

**Comment by spencerccf** [comment]
Are you developing in Objective C?

**Comment by gkrawiec** [comment]
Nope, pure flutter. Newbie here (flutter and dev in general). I created a project with flutter create, then been working on vscode. Other packages I added worked fine. When I added app_settings it stopped working on the iOS simulator. It wouldnt even start debbuging.  After lots of googling I was able to get it to work by opening xcode, creating a swift file, accepting the bridging option and then . deleting the newly created swift file (deleted from inside xcode) and finally editing the podfile with this option

target 'Runner' do
  use_frameworks!

after doing those things app_settings started working on the simulator.
Maybe there is a conflict with other packages? I really dont know much more.

**Comment by spencerccf** [comment]
The default flutter projects are Objective C and Java unless you specify otherwise.  Thanks for the good feedback and details... I'll get this corrected and pushed out.  There shouldn't be any conflicts with other libraries.

**Comment by gkrawiec** [comment]
You mention something along these lines in this comment on a closed issue
https://github.com/spencerccf/app_settings/issues/7#issuecomment-476818522

**Comment by spencerccf** [comment]
Oh snap... that's right... current functionality will require your flutter project to use Swift instead of Objective C.  Been a while and I forgot about that issue.

**Comment by spencerccf** [comment]
You can generate the flutter project using Swift and Kotlin with this command: 
flutter create —org com.myBundleID -i swift -a kotlin my_project_name

**Comment by gkrawiec** [comment]
i'll try to remember that next time I create a project from scratch. thank you for the quick responses.

**Comment by spencerccf** [comment]
No prob.  Also, I just ran a quick test using the default flutter create for Objective C and Java including app_settings Swift plugin.  The only update I had to make was adding "use_frameworks!" to the Runner project's podfile under target 'Runner' do and all worked as just fine.  I'll do some more testing and update readme as needed for future reference.

**Comment by gkrawiec** [comment]
Maybe that's the case and only use_frameworks is all thats needed. I did not test just that. I just kept adding stuff as I found info about it.  "use_frameworks" was the last thing I added.I might try deleting the bridging file later and see if things still work.

**Comment by spencerccf** [comment]
[Found this: "In order to use CocoaPods written in Swift, you must explicitly include use_frameworks! to opt into using frameworks."](https://www.raywenderlich.com/626-cocoapods-tutorial-for-swift-getting-started)
