### ISSUE TITLE
openDeviceSettings opens wrong screen for IOS

### ISSUE THREAD

**Issue by Andrushka1012** [spencerccf/app_settings#151]
On Ios openDeviceSettings launches app settings page after device settings.
Should launch device settings only

**Comment by plinkos** [comment]
This is how Apple designed access: https://github.com/spencerccf/app_settings/issues/153#issuecomment-1275065540

**Comment by dustin-graham** [comment]
> This is how Apple designed access: [#153 (comment)](https://github.com/spencerccf/app_settings/issues/153#issuecomment-1275065540)

@plinkos How does Google Maps pull this off?

https://user-images.githubusercontent.com/959931/196362116-efe56637-1982-4c59-8f27-840a2b7bf49f.mp4

**Comment by plinkos** [comment]
Not sure how that could be unless it's an old version or Google has special permissions/access from Apple.
