### ISSUE TITLE
[iOS] Navigate  to "main setting page" only 

### ISSUE THREAD

**Issue by heedongrichrich** [spencerccf/app_settings#153]
I just used example code to test navigation.

It works but the problem is that every button is navigated to only main-setting page..

Do I have to set anything else?

**Comment by thiagocarvalhodev** [comment]
I'm having the same issue. Doesn't matter which function I call, always it goes to the app settings.

For example:

```dart
if (Platform.isAndroid || forceOpenDeviceSettingsOnIOS) {
    await AppSettings.openNotificationSettings();
    return;
  }
```

**Comment by plinkos** [comment]
Apple doesn't allow navigation to specific settings pages.  There is only support for implementation of a setting like Notifications (you need to handle this on your own in native side with permissions and settings).  Once those settings are implemented and user is prompted to allow then those settings will become available in the App Settings main page.

**Comment by plinkos** [comment]
Feel free to Fork and test in your own branch.  Here are all the private APIs ... However, Apple will most likely reject your app.  Not sure how Google is doing what they are doing or getting away with using private APIs.  If Apple approves your app we can create a new separate iOS open settings feature for calling the private APIs at your own risk.  

prefs:root=General&path=About
prefs:root=General&path=ACCESSIBILITY
prefs:root=AIRPLANE_MODE
prefs:root=General&path=AUTOLOCK
prefs:root=General&path=USAGE/CELLULAR_USAGE
prefs:root=Brightness
prefs:root=General&path=Bluetooth
prefs:root=General&path=DATE_AND_TIME
prefs:root=FACETIME
prefs:root=General
prefs:root=General&path=Keyboard
prefs:root=General&path=INTERNATIONAL
prefs:root=LOCATION_SERVICES
prefs:root=ACCOUNT_SETTINGS
prefs:root=MUSIC
prefs:root=General&path=Network
prefs:root=NIKE_PLUS_IPOD
prefs:root=NOTES
prefs:root=NOTIFICATIONS_ID
prefs:root=Phone
prefs:root=Photos
prefs:root=Sounds&path=Ringtone
prefs:root=Safari
prefs:root=General&path=Assistant
prefs:root=Sounds
prefs:root=General&path=USAGE
prefs:root=VIDEO
prefs:root=General&path=Network/VPN
prefs:root=Wallpaper
prefs:root=WIFI
prefs:root=INTERNET_TETHERING
