### ISSUE TITLE
how to catch back from app setting to flutter

### ISSUE THREAD

**Issue by rifafauzi97** [spencerccf/app_settings#155]
Hi.

How to catch back from app setting to flutter?

I tried this code not work.

```dart
print('Test 1');
await AppSettings.openBluetoothSettings(asAnotherTask: true);
print('Test 2');
```

Because when it's open bluetooth setting, the second print is printed. I expect the second print should be printed after back to flutter.

Any option to catch back from app setting to flutter?

**Comment by plinkos** [comment]
I'll create a PR and add the FlutterResult return to both iOS and Android native side code.  This will allow you to determine if the response is done/completed.

**Comment by Sebastjan-Vuga** [comment]
Hi @plinkos,

Any updates on this matter or how we might catch the "return to the app"?

Thanks!

**Comment by plinkos** [comment]
Apologies for the delay.  I should have this functionality completed today.

**Comment by plinkos** [comment]
Done... new version: 4.2.0 is now available in pub.dev: https://pub.dev/packages/app_settings/

**Comment by chihuy105** [comment]
It's not working in IOS 16 and Android 28
