### ISSUE TITLE
open settings are not awaited

### ISSUE THREAD

**Issue by RobertBrunhage** [spencerccf/app_settings#165]
Opening this as I saw https://github.com/spencerccf/app_settings/issues/99 being merged but it's not working.

**Comment by plinkos** [comment]
I'm doing some more testing... there may be something off still on the Future awaiting properly.  I'll keep everyone posted on what I find.

**Comment by plinkos** [comment]
@RobertBrunhage @AlexHartford @weihenglim

Please try this branch: https://github.com/spencerccf/app_settings/tree/open-settings-are-not-awaited-%23165

You will see that the native side will complete even performing the special callback if passed before executing the next code after the AppSettings call.... i.e. 

          onTap: (() async {
            print('Before Calling AppSettings.openWIFISettings()');
            await AppSettings.openWIFISettings(callback: () {
              print(
                  "** Sample callback function called before anything else gets executed in dart");
            });
            print('After Calling AppSettings.openWIFISettings()');
          })),

Please review this branch and test to ensure it is working as expected.

Thanks

**Comment by plinkos** [comment]
Also, minimum iOS version is now 15.0

**Comment by navaronbracke** [comment]
@RobertBrunhage When updating to Gradle 8, I did remove the callback argument, as using `await` does the same thing and is less confusing. This change should be in version 4.3.0

Also, hey Robert :D
