### ISSUE TITLE
[iOS] Don't await openWIFISettings

### ISSUE THREAD

**Issue by amedeopro** [spencerccf/app_settings#176]
Hello,
i've tried to get local network authorization notification but this code (on your documentation) don't await and go directley on settings and i can't activate local network:

```
                      TextButton(
                          onPressed: () async{
                            await AppSettings.openWIFISettings(callback: () {
                              print('callback wifi settings');
                            });
                          },
```

The problem there are in emulator and phisical device rispectively with iOS 15.7 and 16.5

can you help me?
@plinkos

**Comment by spencerccf** [comment]
The Settings screen will open up first.  The callback that is passed in will be called as soon as the mobile native code call finishes.  So the settings screen will appear before the callback happens but the callback will happen directly after that.

You could also do this:
await AppSettings.openWIFISettings(callback: () {});
 print('this print will happen after the native side code call happens... which doesn't take long');
