### ISSUE TITLE
Breaking change without changing major version number

### ISSUE THREAD

**Issue by 781flyingdutchman** [spencerccf/app_settings#178]
Hi, love the package, but you tripped me up (and am sure will others) by making a breaking change for 4.3.0 without changing the major version number (to 5.0.0).  Flutter packages are supposed to follow [semantic versioning](https://dart.dev/tools/pub/versioning#semantic-versions), and this is so that when I have for example `app_settings: ^4.1.1` in my `pubspec.yaml` file, I can be sure that nothing breaks even when `pub upgrade` updates my package to the latest version __up to but excluding 5.0.0__.  Because you made a breaking change but kept the major at 4, upgrading broke compilation and it took me a while (and reading your changelog) to see that in fact you had made a breaking change. 

So, friendly request next time you make a breaking change to update the major version number :)

**Comment by michalsrutek** [comment]
Same here. Thanks for the package ❤️ But please bump the major version next time there's a breaking change :)

**Comment by spencerccf** [comment]
This has been corrected... apologies for not updating for initial publish.

**Comment by chandrabezzo** [comment]
Hi @spencerccf I was created new [issue](https://github.com/spencerccf/app_settings/issues/182). I think you need retract the version from pub.dev publisher. Thanks.
