### ISSUE TITLE
Retract Published Version at 4.3.0

### ISSUE THREAD

**Issue by chandrabezzo** [spencerccf/app_settings#182]
I see you have published version to [4.3.0](https://pub.dev/packages/app_settings/versions/4.3.0/changelog) with breaking changes. It's make who use this package with caret version like `^4.2.0` will impacted the breaking changes error. So, we need bump the version manually to `5.0.0` or downgrade without caret version `4.2.0`. Can you retract the version from pub.dev publisher?

**Comment by navaronbracke** [comment]
That is not a viable option. The breaking changes are listed in the changelog, as expected. It is up to end users to migrate their usages of the `app_settings` API so that they can use the latest possible versions. It's exactly why we _have_ breaking change notices in the changelog.

**Comment by navaronbracke** [comment]
@spencerccf per the semantic versioning spec https://semver.org/ this release indeed should have its major version updated.

**Comment by navaronbracke** [comment]
@chandrabezzo  Version 5.0.0 is available on pub.dev and 4.3.0 has been retracted

**Comment by fstof** [comment]
So our pipeline is still pulling 4.3.0 and breaking spectacularly...

Anything we have to do to make sure the retracted version is excluded?

our pubspec.yaml is including it with `app_settings: ^4.1.0`

And then we don't have a lock file for this as this is used from a custom package and not an app itself

**Comment by adrianjagielak** [comment]
> So our pipeline is still pulling 4.3.0 and breaking spectacularly...
> 
> Anything we have to do to make sure the retracted version is excluded?
> 
> our pubspec.yaml is including it with `app_settings: ^4.1.0`
> 
> And then we don't have a lock file for this as this is used from a custom package and not an app itself

`app_settings: ">=4.1.0 <4.3.0"`

**Comment by spencerccf** [comment]
I have submitted a request to remove version: 4.3.0 from pub.dev.  I will let you know as soon as it has been removed.

**Comment by jankuss** [comment]
Would it not be possible to issue a patch version 4.3.1, with the breaking change removed? Anybody depending on `^4.3.0` would receive the `4.3.1` version which doesn't have a breaking change. No need to retract.

https://dart.dev/tools/pub/publishing#retract

![image](https://github.com/spencerccf/app_settings/assets/1659532/ede3b2b2-5f69-4c6f-8c46-77e8e5edf4b9)

**Comment by spencerccf** [comment]
Done... patch version 4.3.1 has been published out to pub.dev.  This is essentially same as verson 4.2.0.  So, hopefully all pipelines will start working for y'all again.
