### ISSUE TITLE
AppSettings.openNotificationSettings with app_settings: ^5.0.0

### ISSUE THREAD

**Issue by arnoorani** [spencerccf/app_settings#184]
I get this error while trying to build the flutter application, anyone else dealing with the same? 

Error:: AppSettings.openNotificationSettings
app_settings: ^5.0.0
Flutter 3.7.11

**Comment by navaronbracke** [comment]
What error are you getting specifically?

**Comment by Danzzel** [comment]
The same

**Comment by navaronbracke** [comment]
I meant what stacktrace or error details are you getting from the build output?

**Comment by arnoorani** [comment]
@navaronbracke Member not found: 'AppSettings.openNotificationSettings' that is the error I get

**Comment by navaronbracke** [comment]
@arnoorani You should be using the `AppSettings.openAppSettings(type: AppSettingsType.notification)` instead, as the API has changed since version 5.0.0

This breaking change is mentioned in the changelog. The reason for this is that there is only a single method to open the application settings, instead of one per specific settings type. This makes maintainability easier.

**Comment by Danzzel** [comment]
In my case when I tried to build the IOS app I have an error that open_settings registered twice... Currently, I set v4.3.1 and all works well

**Comment by Danzzel** [comment]
![Screenshot 2023-07-14 at 11 04 57](https://github.com/spencerccf/app_settings/assets/75837219/92e127f6-eba4-45fb-98e3-095f2fbf9703)
on 5.0.0 only

**Comment by quoc-huynh-cosee** [comment]
I'm receiving this error with 5.0.0 running `pod update`.
```
[!] CocoaPods could not find compatible versions for pod "app_settings":
  In Podfile:
    app_settings (from `.symlinks/plugins/app_settings/ios`)

Specs satisfying the `app_settings (from `.symlinks/plugins/app_settings/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by cyiboy** [comment]
having the same error as @quoc-huynh-cosee any fix?

**Comment by peter9teufel** [comment]
Got the same today, looks like setting the deployment target to iOS 16 is now required, as soon as I changed the deployment target to iOS 16 pod install/update worked.

**Comment by quoc-huynh-cosee** [comment]
@cyiboy No, so far not.

**Comment by cyiboy** [comment]
> @cyiboy No, so far not.

for now, I upgraded to 'platform: ios 15' in my podfile and it worked for me

**Comment by large** [comment]
I still use 4.1.8 (since it work fine for me, and I want to keep iOS 13 as minimum). But I also get the

```
[!] CocoaPods could not find compatible versions for pod "app_settings":
  In Podfile:
    app_settings (from `.symlinks/plugins/app_settings/ios`)

Specs satisfying the `app_settings (from `.symlinks/plugins/app_settings/ios`)` dependency were found, but they required a higher minimum deployment target.
```

Could it be that you have set the iOS requirements for all the old versions too?

**Comment by peter9teufel** [comment]
Got the same issue now, I have a second app which should be compatible back to iOS 13, keeping any of the older app_settings version (4.3.1, 4.2.0, 4.1.8) does not change the fact that app_settings requires now iOS 15.

**Comment by navaronbracke** [comment]
`app_settings` only sets the iOS deployment version to 11.0 in the podspec file, so I don't see why it would be a problem?

Does the version `5.0.0` example app not work for anyone? 

I do notice that the podspec still lists `4.3.0` as version on master though

**Comment by navaronbracke** [comment]
Apparently, the example app does not build for me with XCode 14.3.1 (14E300c) and CocoaPods 1.11.2

Investigating now

**Comment by irunatbullets** [comment]
All of a sudden I too have this issue with app_settings 4.1.6 while trying to release a quick fix for my application:
```
[!] CocoaPods could not find compatible versions for pod "app_settings":
  In Podfile:
    app_settings (from `.symlinks/plugins/app_settings/ios`)

Specs satisfying the `app_settings (from `.symlinks/plugins/app_settings/ios`)` dependency were found, but they required a higher minimum deployment target.
```
The latest version of app_settings I can move to is 4.3.1 without having to update the SDK version - however, this doesn't solve the issue.

I want to avoid updating too many things because I'm trying to fix only one line of code. My app isn't used all the time, but when it is used, I have to avoid making significant changes because it can impact people.

```
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.2"
```

**Comment by navaronbracke** [comment]
Does the CocoaPods error specify what "higher deployment target" value is actually is?

IIRC Flutter dropped support for iOS 10 a while back, so the minimum iOS version is 11.0 now.

**Comment by navaronbracke** [comment]
Could you all try `pod install --repo-update` ?

**Comment by large** [comment]
I had a fork of 4.1 1 untouched, that can be used on older versions

  `app_settings: 
     git: 
       url: https://github.com/large/app_settings.git`

**Comment by navaronbracke** [comment]
I'll see if I can reproduce with the old 4.3.0 on iOS 13. I'll report back if I find anything

**Comment by irunatbullets** [comment]
I have been able to get past this issue by using app_settings 4.3.1 and setting `platform :ios, '15'` in my Podfile. I checked firebase for the lowest version of iOS using my app and there is nothing below that.

**Comment by navaronbracke** [comment]
@irunatbullets what is the deployment target of the Firebase plugin that you use?

**Comment by irunatbullets** [comment]
@navaronbracke Is this what you're asking for?

```
  # Firebase
  firebase_core: ^2.3.0
  # Crashlytics logs
  firebase_crashlytics: ^3.0.6
  # Firebase cloud messaging, used for notifications
  firebase_messaging: ^14.1.1
  ```

**Comment by navaronbracke** [comment]
With those versions, I can figure out the deployment version in their iOS settings :)

I just want to figure out if these set a different deployment target, confusing Cocoapods as a result.

**Comment by navaronbracke** [comment]
@irunatbullets I can build and run the app if I use the fixes in #186 

Without my fixes, it fails with the following logs (even on v4.3.0)
[v4.3.0_logs.txt](https://github.com/spencerccf/app_settings/files/12169674/v4.3.0_logs.txt)

The minimum deployment target of the example app is iOS 11.0

I even added your Firebase dependencies:

```
  firebase_core: 2.3.0
  firebase_crashlytics: 3.0.6
  firebase_messaging: 14.1.1 
```

and even then Cocoapods adds them to my Podfile.lock without issues.

Could you try using my PR as a git override, just to test it?

```
app_settings: 
   git: 
     url: https://github.com/navaronbracke/app_settings.git
     ref: fix_v5_ios_compile
```

**Comment by irunatbullets** [comment]
@navaronbracke I tried, but 

```
The current Dart SDK version is 2.18.2.

Because APPNAME depends on app_settings from git which requires SDK version >=2.19.0 <4.0.0, version solving failed.
pub get failed (1; Because APPNAME depends on app_settings from git which requires SDK version >=2.19.0 <4.0.0, version solving failed.)
exit code 1
```
I'm happy to stick with 4.3.1 and ios 15 because I'm able to build and not change anything else.

**Comment by navaronbracke** [comment]
I'll see if I can lower the Dart version of the plugin (afaik there isn't anything that we use that requires Dart 2.19, so I could just drop back down to 2.17 or something?)

**Comment by navaronbracke** [comment]
@irunatbullets I pushed a commit that lowers the Dart constraint to 2.18.0 (requires Flutter 3.3.0).

Let me know if that is sufficient for you.

**Comment by irunatbullets** [comment]
> @irunatbullets I pushed a commit that lowers the Dart constraint to 2.18.0 (requires Flutter 3.3.0).
> 
> Let me know if that is sufficient for you.
> 
> The original jump to Flutter 3.7 was for Gradle 8 stuff iirc.

Thank you very much, that works.

**Comment by mitulsavani** [comment]
Our team is facing the same issue.
Current Min deployment is ios 14.

This is a prod application for our client. Let me know @navaronbracke  what is the sustainable way to resolve this issue (Not in a position to increase the minD to ios 15).

Attaching the screenshot below for your reference.
![Screenshot 2023-09-11 at 10 30 46 PM](https://github.com/spencerccf/app_settings/assets/22231691/bd7b052f-a052-47fe-b86f-06ffc43f391d)

**Comment by navaronbracke** [comment]
@mitulsavani As mentioned in https://github.com/spencerccf/app_settings/issues/184#issuecomment-1651210127
I have a patch that allows an app using `app_settings` to run with iOS 11 as minimum deployment target.

Could you try a git dependency like this?

```
app_settings: 
   git: 
     url: https://github.com/navaronbracke/app_settings.git
     ref: fix_v5_ios_compile
```

I tested again using a `flutter create`d app using Flutter 3.13 (has min deployment target of iOS 11) and ran it on an iOS 14.0 Simulator. This should be a short term fix for you.

The long term fix is that @spencerccf reviews and merges the fix in https://github.com/spencerccf/app_settings/pull/186 and then publishes the new version on pub.dev (Version 5.1.0 was also not published, hence why I mention the publishing part as well)

**Comment by mitulsavani** [comment]
That sounds good to me! For now, we will go ahead and use the above mentioned patch.
Thank you for your response.

**Comment by minhdang2803** [comment]
> I have been able to get past this issue by using app_settings 4.3.1 and setting `platform :ios, '15'` in my Podfile. I checked firebase for the lowest version of iOS using my app and there is nothing below that.

This worked!
