### ISSUE TITLE
Calling to AppSettings.openAppSettings(type: AppSettingsType.location) does not open location permission screen

### ISSUE THREAD

**Issue by rasuldev** [spencerccf/app_settings#185]
Opens this screen:
![изображение](https://github.com/spencerccf/app_settings/assets/4163864/188f0265-3d79-4b74-b1a6-604d8bb4c62e)

instead of this:
![изображение](https://github.com/spencerccf/app_settings/assets/4163864/92b6fafc-8efc-43ff-9cff-bff88a5d8030)

**Comment by navaronbracke** [comment]
On Android you cannot open the permission settings for a specific app. The best we can do is redirect you to the Settings for the app.

**Comment by joaoantoniomartinsfilho** [comment]
Hello @navaronbracke how are you doing? 

Do you have the link of the docs explain why we cannot open the permission settings for a specific app? 

Have a nice weekend! 

Kind regards.

**Comment by navaronbracke** [comment]
In https://developer.android.com/reference/android/provider/Settings there is no specific constant for the location permission specifically. The documentation for `ACTION_SECURITY_SETTINGS` mentions

```
Show settings to allow configuration of security and location privacy.
```
but I'm not sure what "location privacy" means here.
The security settings can be opened with app_settings already.

We already use `ACTION_APPLICATION_DETAILS_SETTINGS` in the plugin to show the application settings page for a specific package name (currently it only uses the package name of the current application, but that can be improved to allow a package name argument). However, that one only opens the general settings page for an app, as you mentioned before.
