### ISSUE TITLE
url noted as publisher name (nupner.com) on pub.dev is blocked by some antivirus (Sophos)

### ISSUE THREAD

**Issue by localpcguy** [spencerccf/app_settings#188]
Not sure if this is a false positive, but when I tried to access the nupner.com domain (listed as the publisher on [pub.dev](https://pub.dev/packages/app_settings)), I got the following message. While this does not appear to have anything specifically to do with the package, anyone doing due diligence on the package may see this as a red flag. 

To be clear (and for anyone reading this), I am not saying this should reduce confidence in this package and I did look through the code and I did not see any reason for concern with this package. 
 
![image](https://github.com/spencerccf/app_settings/assets/593240/f1bd0c9b-7278-4869-a8c1-fa14256e47df)

![image](https://github.com/spencerccf/app_settings/assets/593240/09fe58a6-63cd-444a-b0c2-dbf67359ba47)

**Comment by spencerccf** [comment]
I own the domain and just don't have a website up and running at this time.  I also own the company: Nupner Innovations, LLC. The website work is still in progress. I chose to use my domain as valid publisher so it's not just anonymous or un-verified etc.  To have a publisher out there in pub.dev you have to be verified via DNS entry etc.  So even though the website doesn't have an SSL or any particular content it's legit and has been verified by pub.dev.

**Comment by localpcguy** [comment]
I have seen false positives by Sophos before, I figured it was probably something of that nature. Figured better to let you know than to assume though. Thanks for the response.
