### ISSUE TITLE
[iOS] Open wifi setting doesn't work correctly

### ISSUE THREAD

**Issue by chounry** [spencerccf/app_settings#192]
- Device: iPhone X
- OS version: 15.6
- Package version: 5.0.0

When I tried `AppSettings.openAppSettings(type: AppSettingsType.wifi)`, it opens a wrong setting like the image below. On android, it works fine.

<img src="https://github.com/spencerccf/app_settings/assets/29001338/a5914b7a-2c00-4342-9edb-a99ba1e56171" width=20%>

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.5 22G74 darwin-x64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/imac/Documents/flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)            
    • iPhone 14 (mobile) • 373432E7-65AD-424E-8E3C-4B8C593148F2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

Thank you

**Comment by Galeen-Bidpath** [comment]
Same on my side. iPhone X 16.6.1 and iPad 16.3.1

**Comment by bdesilvaA** [comment]
Same here
iPhone 12 mini
iOS 16.6.1

**Comment by JooYoo** [comment]
same here...  It actually opens settings home view.

**Comment by yanashenyang** [comment]
same here

**Comment by JeffyLo94** [comment]
> * Device: iPhone X
> * OS version: 15.6
> * Package version: 5.0.0
> 
> When I tried `AppSettings.openAppSettings(type: AppSettingsType.wifi)`, it opens a wrong setting like the image below. On android, it works fine.
> 
> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/29001338/264516562-a5914b7a-2c00-4342-9edb-a99ba1e56171.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMjUwODcsIm5iZiI6MTcwNjEyNDc4NywicGF0aCI6Ii8yOTAwMTMzOC8yNjQ1MTY1NjItYTU5MTRiN2EtMmMwMC00MzQyLTllZGItYTk5YmExZTU2MTcxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE5MzMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZDA3N2M3YzcyOTZmY2IyYzYwZTNlMGE1YWRjNTE2OGRlMjAyODQ2YWUzZmFlYTkwYTE0MTQzNmMxMWFkMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m2a51PpiTVjTiNJPwvsyaTXEv2s5fvCrPuqWwR8Jx2A">
> `flutter doctor -v`
> 
> ```
> [✓] Flutter (Channel stable, 3.10.5, on macOS 13.5 22G74 darwin-x64, locale en-US)
>     • Flutter version 3.10.5 on channel stable at /Users/imac/Documents/flutter-sdk
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
>     • Engine revision 45f6e00911
>     • Dart version 3.0.5
>     • DevTools version 2.23.1
> 
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.
> 
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 14E222b
>     • CocoaPods version 1.12.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
> 
> [✓] VS Code (version 1.81.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.70.0
> 
> [✓] Connected device (3 available)            
>     • iPhone 14 (mobile) • 373432E7-65AD-424E-8E3C-4B8C593148F2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
>     • macOS (desktop)    • macos                                • darwin-x64     • macOS 13.5 22G74 darwin-x64
>     • Chrome (web)       • chrome                               • web-javascript • Google Chrome 116.0.5845.140
> 
> [✓] Network resources
>     • All expected network resources are available.
> 
> ! Doctor found issues in 2 categories.
> ```
> 
> Thank you

AppSettingsType.wifi is only supported for Android
