### ISSUE TITLE
 Duplicate interface definition for class 'AppSettingsPlugin'

### ISSUE THREAD

**Issue by leredirect** [spencerccf/app_settings#193]
Flutter 3.13.2
app_settings: 5.0.0
got exception for IOS only: 

![Frame 2](https://github.com/spencerccf/app_settings/assets/71591796/796202e1-78c4-4434-9e16-b43ce010ea0b)

worked fine on 4.2.0

**Comment by RiccardoCherchi** [comment]
I have the same issue, right now i decided to downgrade to te previous version (4.2.1) and it's working. Waiting for new updates on this thread

**Comment by WieFel** [comment]
+1

**Comment by tinncdev** [comment]
+1

**Comment by navaronbracke** [comment]
Does this reproduce after running a `flutter clean` and using `app_settings: 5.1.1` ?

What Flutter version are you using?
