### ISSUE TITLE
On iOS, Can't Go Back to App After Opening Location Settings.

### ISSUE THREAD

**Issue by muhammad-mohsen-innuva** [spencerccf/app_settings#199]
Hi,

Sorry if this sounds stupid...I'm calling `AppSettings.openLocationSettings()` (version 4.1.8) to open the location settings on iOS, everything is working fine, except, I can't go back to the app unless I go to the app switcher.

I noticed that sometimes an arrow in the upper left corner of the screen appears when opening the settings (when using the _permission_handler_ library to open the location settings as in the screenshot below)

![image](https://github.com/spencerccf/app_settings/assets/145488991/7a3823f4-6c18-4aa2-8852-c2d284021a17)

Is there something I can do to show this back arrow?
I looked around and couldn't find anything useful, and again sorry if this sounds stupid, I'm not familiar with iOS.

**Comment by navaronbracke** [comment]
This arrow is handled by the OS if you open the Settings app from a different app.
That's why the name of the app is shown there as well.

Could you try with the latest version of the plugin?

**Comment by pamafe1976** [comment]
This happens to my app when going to me. There is no arrow to return to the app.
I'm using 
  app_settings  5.1.1    
```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale es-AR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.1)
[✓] Connected device (5 available)
[✓] Network resources
```

**Comment by spencerccf** [comment]
This is default behavior of iOS.
