### ISSUE TITLE
Fatal Exception on android KitKat and below

### ISSUE THREAD

**Issue by chrispypatt** [spencerccf/app_settings#20]
Hi, I am using this plugin for my flutter app and had my min SDK set to 16. I noticed one of my beta testers kept crashing on startup with the error message below so I investigated. I found that I can reproduce this same error on any device with android sdk 19 and below (KitKat). In the meantime, I bumped my minsdk to 21 and everything works fine.

I may be doing something wrong but if anyone has any insight or has seen this before please let me know!

pubspec includes:  ` app_settings: 1.0.6+2`

in bundle.gradel `ext.kotlin_version`  is set to  `'1.3.21'`

Let me know if nay other information would be useful. Thanks!
```
Fatal Exception: java.lang.NoClassDefFoundError: kotlin.jvm.internal.Intrinsics at 
    com.example.appsettings.AppSettingsPlugin$Companion.registerWith(AppSettingsPlugin.kt) at 
    com.example.appsettings.AppSettingsPlugin.registerWith(AppSettingsPlugin.kt) at 
    io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:33) at
    com.CP.Savour.MainActivity.onCreate(MainActivity.java:11) at     
    android.app.Activity.performCreate(Activity.java:5372) at 
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104) at 
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257) at 
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349) at 
    android.app.ActivityThread.access$700(ActivityThread.java:159) at 
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) at 
    android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:176) 
    at android.app.ActivityThread.main(ActivityThread.java:5419) at 
    java.lang.reflect.Method.invokeNative(Method.java) at 
    java.lang.reflect.Method.invoke(Method.java:525) at 
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046) at 
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862) at 
    dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by spencerccf** [comment]
I'll check into this for minSdkVersion 16.

**Comment by spencerccf** [comment]
There are differences in how older Android SDKs handle asking for permissions.  I believe starting in API 20 and up Android permissions went from asking at app install to asking from within the app when the services were going to be used.  This plugin is build to use the later API 20 and up which will not work on anything below.  They are two different paradigms... old one used to ask for permissions upon app install and all new APIs ask after install when particular app service use is requested.
