### ISSUE TITLE
How to open data roaming setting

### ISSUE THREAD

**Issue by thang510023** [spencerccf/app_settings#22]
Hi, I am using your library in my project, and need to open the mobile data settings, can you update that part?

**Comment by spencerccf** [comment]
Unfortunately the use of App-Prefs or prefs:root are no longer allowed for iOS apps as they are private APIs.  Any iOS app using these types of calls will get rejected by Apple.  The default is to open the settings specific to the app in use.

**Comment by spencerccf** [comment]
However, I can get this added for the Android side of the plugin.  The iOS side will behave as it does today... so that will give you some additional functionality that is still allowed on Android.

**Comment by spencerccf** [comment]
@thang510023 This has been added to the Android side of the plugin.  iOS will still open App Settings.

**Comment by spencerccf** [comment]
@thang510023 - This has been added to the Android side of the plugin. iOS will still open App Settings.  Closing out this issue... please let me know if you have any questions or need additional feature adjustments.

**Comment by thang510023** [comment]
Sorry, I didn't follow my github account, glad you edited it for me and everyone, wish you success in the future, thank you very much.
