### ISSUE TITLE
`openAppSettings` opens wrong screen on Android

### ISSUE THREAD

**Issue by pro100svitlo** [spencerccf/app_settings#26]
When I call `AppSettings.openAppSettings();` on Android it opens the `app storage settings` screen, instead `app settings`.

**Comment by spencerccf** [comment]
@pro100svitlo I'm checking into this now to see what's happening.

**Comment by spencerccf** [comment]
@pro100svitlo  I've tested in both the example project within the plugin repo and a fresh Flutter project using the latest 2.0.2 from https://pub.dev/packages/app_settings and both open the settings for the current app i'm using correctly.  The information I see is: Force Stop, Uninstall, Show Notifications, Storage, Cache, Launch By Default options, and Permissions.  Can you upload a screen image of what you are seeing?

**Comment by spencerccf** [comment]
@pro100svitlo Just wanted to follow up with you on this issue to see if you had any screen images to provide of what you are seeing on your end?

**Comment by spencerccf** [comment]
@pro100svitlo Closing this issue at this time.  Please let me know if you need any additional help.

Thanks
