### ISSUE TITLE
need callBack function for opening settings. 

### ISSUE THREAD

**Issue by krishnaaro** [spencerccf/app_settings#27]
please tell if i'm missing something,

**need a callback function after closing settings.**

i was using location which is mandatory in my application, so i need to check location is turned on or not after closing the settings screen.

**Comment by spencerccf** [comment]
You can solve the issue in Flutter side using didChangeAppLifecycleState override.  This will allow you to detect when the app goes into background which it will when you open settings.  Then when app comes into foreground after user updates the location settings you can detect and re-prompt user to accept location access and then start tracking location etc.

Sample override that I've used in my app:

  /// Check for app life cycle changes and perform any updates that are needed
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused) {
      _appIsInBackground = true;
      stopLocationAccess();
    }
    if (state == AppLifecycleState.resumed && _appIsInBackground) {
      _appIsInBackground = false;
      restartLocationAccess().then((done){
        positionRequestBloc.requestPosition();
      });
    }
  }

There is no way (that I know of) to tack on a callback to the native settings screen after user changes a setting and leaves that screen.  Detecting application state change is a solid way to determine what your app is doing.

**Comment by krishnaaro** [comment]
Cool
