### ISSUE TITLE
my swift_version is 5.0 

### ISSUE THREAD

**Issue by zzb999** [spencerccf/app_settings#29]
Xcode's output:
↳
    === BUILD TARGET firebase_messaging OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/x/Development/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/app_settings-1.0.6/ios/Classes/AppSettingsPlugin.m:2:9: fatal error: 'app_settings/app_settings-Swift.h' file not found
    #import <app_settings/app_settings-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the precompiled application for the device.
Error launching application on Device.
Exited (sigterm)

**Comment by plinkos** [comment]
There is a change that Apple did where Swift 4 compiled plugins will not work with Swift 5 compiled apps.  I will push up a Swift 5 update ASAP to correct this problem.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by spencerccf** [comment]
@zzb999 I published a new version 3.0.0 that supports Swift 5.0.1.   Please update to this latest version and re-run your project.  Please let me know if you have any issues.

**Comment by zzb999** [comment]
Xcode's output:
↳
    error: SWIFT_VERSION '5.0.1' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'app_settings')
    warning: The iOS deployment target is set to 4.3, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'FMDB')
    warning: The iOS deployment target is set to 6.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'Reachability')
    note: Using new build systemnote: Planning buildnote: Constructing build description

**Comment by spencerccf** [comment]
@zzb999 - My apologies... please update plugin again: 3.0.0+1... I missed a change to the .podspec.

**Comment by zzb999** [comment]
thank you

**Comment by entonio** [comment]
I'm having this issue on Xcode 11.3.1 on Mojave when trying to add a flutter module to an app using the Podfile / install_all_flutter_pods approac described in 'Option A' at https://flutter.dev/docs/development/add-to-app/ios/project-setup. I'm using 3.0.0+1. What can I do?
