### ISSUE TITLE
openLocationSettings opening just device setting on IOS

### ISSUE THREAD

**Issue by Xgamefactory** [spencerccf/app_settings#33]
**app_settings: ^3.0.0+1**
What setting we should define in order to open location settings (under privacy) not just phone settings page.We need to forward user to the page where he can enable locations settings.

> Platform Specifics #
> The following setting options available on both iOS and Android: openAppSettings, openWIFISettings, openLocationSettings, openSecuritySettings, openBluetoothSettings, openDataRoamingSettings, openDateSettings, openDisplaySettings, openNotificationSettings, openSoundSettings
> 
> iOS #
> All three options open the current 'app' settings section if there are settings defined. If no current settings are defined for the app the iPhone Settings Screen will be displayed.

**Comment by plinkos** [comment]
You will need to initially ask for location permissions via the LocationManager before you will be able to see location settings option under app settings.  The openLocationSettings is used for asking user to enable the location settings after you have asked them initially via LocationManager like this....


override func viewDidLoad() {
    super.viewDidLoad()

    locationManager = CLLocationManager()
    locationManager?.delegate = self
    locationManager?.requestAlwaysAuthorization()

}

The request authorization will cause the OS to provide user with OS built in alert which the text is based off of permissions strings entered in the info.plist (required to use location access).  The only way on iOS for location settings to appear in app settings when you call openLocationSettings is to ask for access initially via the default native way by using LocationManager. 

Please let me know if you have any questions. 

Thanks. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Xgamefactory** [comment]
thanks for response. but app already given location permission.
we need redirect user to location settings when location service is turned off.

**Comment by plinkos** [comment]
The location settings for the app will appear In the app setting which will open up when using openLocationSettings method.  If the user turned off location settings at the OS system level on iOS there is no way to send user to that specific section of settings as Apple doesn’t allow that.  If you have the location settings setup to ask in your app and user doesn’t allow access when asked you can send them to the app’s location settings directly by using openLocationSettings.  

Thanks


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by spencerccf** [comment]
@Xgamefactory Did my explanation make sense?  Were you able to get everything up and running?

Thanks

**Comment by bambinoua** [comment]
So how to naviagate use to **Location Settings** (not **Application Settings!**) when location services are off?
So I need to open this screen
[https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/ios13-iphonexs-settings-privacy-location-services.png](url)

**Comment by spencerccf** [comment]
iOS will not allow you to navigate to "Location Settings" Apple restricts doing that in newer versions of iOS.  You will only be able to see and access location settings for your application after you have asked for permission and user has granted access.  After user grants access to location on their phone you then will be able to see "Location Settings" under the "App Settings" for you app which will open up programmatically when using the "openLocationSettings" method in the app_settings plugin.  * PLEASE Remember * the user must have been asked and accepted location access in order for you to be able to view location settings within the Application Settings screen.

**Comment by spencerccf** [comment]
@bambinoua - You can use this plugin to ask for location access/permissions for both iOS and Android: https://pub.dev/packages/geolocator  after that has been done you will be able to use "openLocationSettings" to view/change location access for your application.

**Comment by bambinoua** [comment]
By the way I could open _Location Settings_ (when Location Service off for all apps) using this work around.

    final url = 'App-Prefs:root=Privacy&path=LOCATION';
    if (await canLaunch(url)) {
        await launch(url);
    }
Of course I understand that it is not allowed for publishing app but for personal needs it looks like working.

**Comment by spencerccf** [comment]
Yes, that will work but def not supported by Apple anymore.  Great for personal use app but will most likely get rejected by Apple when submitting to App Store.

**Comment by sanju-developer** [comment]
With permission_handler: ^5.0.0+hotfix.8 this version.

I'm unable to open location page of application in setting, it just open setting page.

Could you please let me know what can I do 😁 ?

**Comment by plinkos** [comment]
On iOS you will not be able to open location settings screen.  You can prompt user for location access in your app at anytime.  Once user has given access the openLocationSettings will display the overall app settings which will include the location settings.  Again, Apple doesn’t allow the use of the workaround to open location settings screen specifically.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
