### ISSUE TITLE
Android openNotificationSettings opens Do Not Disturb

### ISSUE THREAD

**Issue by agersea** [spencerccf/app_settings#34]
Android Emulator Pixel 3 XL

When calling AppSettings.openNotificationSettings the device navigates to Do Not Disturb settings.

Additionally, it interrupts the app history and does not allow for easy navigation back to the calling Flutter application

app_settings: ^3.0.0+1

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

**Comment by spencerccf** [comment]
What version of Android OS are you running?   I will setup Pixel 3 XL with that version and try to replicate what you are seeing.  The navigation back to the calling Flutter application is standard Android navigation... use the system back button.  iOS offers a back to app link in the upper left of the window but Android doesn't and expects the native built in back button to be used.  There is no way to add a back button to that native Android screen that is being called from a separate application.

**Comment by CodeDruid13** [comment]
Happens also on my end. It opens do no disturb settings permission Samsung J4 plus.

**Comment by Jan-pp** [comment]
Same issue on my Galaxy S6 with Android 7.0. It opens the DND page instead, but it does show the top-left back button which works fine.

However when I choose to open app settings it does not show the back button and the hardware back button doesn't work either.

**Comment by aqwert** [comment]
Looking at the [code](https://github.com/spencerccf/app_settings/blob/master/android/src/main/kotlin/com/example/appsettings/AppSettingsPlugin.kt) it uses `ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS` which is for [Do not Disturb](https://developer.android.com/reference/android/provider/Settings#ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS) 

Looking around the place it could use [APP_NOTIFICATION_SETTINGS](https://stackoverflow.com/questions/32366649/any-way-to-link-to-the-android-notification-settings-for-my-app) for Android 8 and above  or [ACTION_APPLICATION_DETAILS_SETTINGS](https://stackoverflow.com/questions/38124552/access-application-notification-settings-programmatically)

May need to checked and it could be dependant on the Android version.

**Comment by plinkos** [comment]
We will need to add a Android version check and swap out the setting accordingly.  Anyone interested in taking this one on and creating a PR?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ebsan** [comment]
I'm still having issues with API version 24. The StackOverflow and documents show that APP_NOTIFICATION_SETTINGS cannot be relied on for versions prior to API 26. In https://github.com/spencerccf/app_settings/blob/980228376a0b7fb4e4117709d053376cb3b1b4f8/android/src/main/kotlin/com/example/appsettings/AppSettingsPlugin.kt#L67 should be changed to `>= 26 `not 21.
