### ISSUE TITLE
Support Settings.Panel on Android Q

### ISSUE THREAD

**Issue by navaronbracke** [spencerccf/app_settings#37]
I was wondering if we could support using the new Settings.Panel API on Android Q and up?

**Comment by plinkos** [comment]
Yep, I think we can do that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by spencerccf** [comment]
@navaronbracke - This is in progress...

**Comment by vargavince91** [comment]
While the update to this library is in progress... I worked on a small Android-only package exactly for this feature: [`settings_panel_android`](https://pub.dev/packages/settings_panel_android)

**Comment by spencerccf** [comment]
@vargavince91 Why not create a PR and add to app_settings library?

**Comment by houdayec** [comment]
@spencerccf Any news? Did you implement it?

**Comment by navaronbracke** [comment]
@plinkos I can take another look at this one if you want?

**Comment by spencerccf** [comment]
@navaronbracke Yes, please.  Thank you!

**Comment by navaronbracke** [comment]
@spencerccf  Should be done in #175 :)
