### ISSUE TITLE
Enhancement: Open the 'app' settings menu on Android

### ISSUE THREAD

**Issue by jamespfinn** [spencerccf/app_settings#4]
The current version of `app_settings` allows for the system Wifi, Location, and Security menus to be accessed, but not the 'app' settings menu as experienced on iOS.

I will submit a PR to allow for this functionality on Android.

**Comment by spencerccf** [comment]
Thanks for adding the new Android functionality... will review and get merged.

**Comment by jamespfinn** [comment]
Happy to help, thanks for the merge!
