### ISSUE TITLE
Android Bluetooth Settings opens App Settings

### ISSUE THREAD

**Issue by StarostaIZ** [spencerccf/app_settings#40]
Testing on Samsung Galaxy S7 Edge

When calling openBluetoothSettings the device opens app settings.

On emulator everything works fine (oreo 8.1) 
app_settings: 3.0.0+1
Flutter doctor:

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale pl-PL)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (12 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Maciek\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM G935F • ce04160473d5d11d05 • android-arm64 • Android 8.0.0 (API 26)

**Comment by plinkos** [comment]
Ok, I have some new Android updates to put into the plugin and will debug this as part of those updates. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by spencerccf** [comment]
@StarostaIZ what permissions do you have setup in your AndroidManifest.xml file for Bluetooth access?  You will need to provide access permissions there in order to use this feature.  The app settings plugin defaults to opening your app settings screen upon exception thrown... usually results from permission access.

**Comment by spencerccf** [comment]
@StarostaIZ Is this still an issue for you?

**Comment by StarostaIZ** [comment]
Sorry, forgot to answer last time. I added bt permissions and it works just as I wanted, thanks :)
