### ISSUE TITLE
Option to open HotSpot settings screen

### ISSUE THREAD

**Issue by psycura** [spencerccf/app_settings#41]
Hello, and thank you for this awesome plugin.
Is it possible to add support for opening HotSpot settings screen?

**Comment by spencerccf** [comment]
Yes, we can get this added.

**Comment by ArvindNagaonkar** [comment]
Can someone give me basic guidance about this?
I like to do this as quickly as possible.

**Comment by mcfugger** [comment]
Hi, please checkout my pull request #135

**Comment by mcfugger** [comment]
> Hi, please checkout my pull request #135

It was tested on Android 10 and Android 11 phones successfully.
