### ISSUE TITLE
compileSdkVersion 28??????? Android R's first developer preview is already out

### ISSUE THREAD

**Issue by flutter2k20** [spencerccf/app_settings#42]
Hi,

Is there any particular reason why the compileSdkVersion is still 28? 

Thanks!

**Comment by spencerccf** [comment]
With this being a major release of Android we can offer a higher compileSdkVersion in a new Major version of the plugin.  Stay tuned please.

**Comment by spencerccf** [comment]
@flutter2k20 available now in latest release 4.0.0

**Comment by flutter2k20** [comment]
Perfect, Thanks! In time for our next app release version :)
