### ISSUE TITLE
app_settings functions not working :( 

### ISSUE THREAD

**Issue by uzairleo** [spencerccf/app_settings#48]
Hi there! 
i am uzair leo today i m using this flutter package but its not working for me its getting an exception  and saying me that `wifi function not found on channel app_settings` 
.i will also share my screensshots with u guys hope it help to understand my problem. 

![Screenshot (943)](https://user-images.githubusercontent.com/52172428/80305866-16e54a80-87d9-11ea-8f07-13df83619987.png)

**Comment by spencerccf** [comment]
@uzairleo Is this still an issue?  Did you ensure that you loaded the libraries and build before attempting to use them?  Sometimes you need to build the app before plugins get recognized properly.  Also, look at the sample app in the plugin... all the calls are in there for reference.

Thanks

**Comment by uzairleo** [comment]
yes and that's why now i am using alternativs of thid

**Comment by spencerccf** [comment]
Get latest version: 4.0.1+1
