### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by nickpnmrv** [spencerccf/app_settings#50]
Trying to build the iOS app after adding the dependency on app_settings package fails:
'app_settings/app_settings-Swift.h' file not found
![image](https://user-images.githubusercontent.com/28644944/82237811-89f46380-9936-11ea-9644-0258dfea4e47.png)

**Comment by plinkos** [comment]
You need to set the iOS side of your Flutter project to Swift instead of Objective C

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JobMoll** [comment]
Hey, i got the same problem. How can i change my flutter project to swift?

Regards,

**Comment by nickpnmrv** [comment]
It looks like the problem is with the new Build System: File -> Workspace Settings -> Build System. Hoever I coul not change it to the old one because of other package, so I have decided not to use app_settings package and created my ows Singleton, that would deal with configuration

**Comment by spencerccf** [comment]
I will work on this issue today ... Flutter defaults to Objective C for iOS when you create a new project.  Would be nice if they used Swift ;)  There are some setting adjustments that need to be done on the iOS side and I will work on getting those updated and pushed out.

Sorry for the delay.

**Comment by spencerccf** [comment]
Closing this issue as it has to deal with a Flutter limitation between Swift plugins and Objective C projects and if corrected by https://github.com/spencerccf/app_settings/issues/50#issuecomment-634034725
