### ISSUE TITLE
Could not determine the dependencies of task ':app_settings:compileReleaseAidl'

### ISSUE THREAD

**Issue by anandarch** [spencerccf/app_settings#57]
Could not determine the dependencies of task ':app_settings:compileReleaseAidl'.
> Failed to find Platform SDK with path: platforms;android-R

build.gradle
compileSdkVersion 29

pubspec.yaml
  app_settings: ^4.0.1

**Comment by spencerccf** [comment]
You need to install Android-R... Tools > SDK Manager and download.

**Comment by anandarch** [comment]
Hi @spencerccf ,

Thank you for your reply, getting below error now

Failed to find Platform SDK with path: platforms;android-R

**Comment by m-fenix2112** [comment]
me too ^^ I have android R did update app_sitting to 4.0.1+1
still having the erorr

**Comment by anandarch** [comment]
@m-fenix2112, 
You might have to change compileSdkVersion to 30 and accordingly you may have change kotlin_version to 1.30.70 and distributionUrl to https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

**Comment by m-fenix2112** [comment]
Working perfectly 👏

**Comment by plinkos** [comment]
Thank you @anandarch 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by anandarch** [comment]
Glad that it worked for you @m-fenix2112 and @plinkos 
Closing this ticket since we have workaround now.
