### ISSUE TITLE
Enhancements : generic and languages settings

### ISSUE THREAD

**Issue by houdayec** [spencerccf/app_settings#58]
Hello,

### First of all, thanks for maintaining this library, great job.

I would like to know if it is possible to add methods to be redirected on the main screen of settings for Android and also to be redirected on the language settings screen. It would be very interesting! 

Thanks in advance.

**Comment by ibraheemalayan** [comment]
This issue is closed as completed, but I did not find a way to open preferred language settings page on IOS.
The youtube app opens it when a user tries to change the language, this means it is possible.

Are there any plans to add it ?
