### ISSUE TITLE
App is crashing on start

### ISSUE THREAD

**Issue by asifjavaid** [spencerccf/app_settings#60]
Hi guys,

My flutter application was running smooth. I have added app_settings: 4.0.1+1 package. And then I am getting the following error while the app is crashing.
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
        at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
        at com.example.appsettings.AppSettingsPlugin$Companion.registerWith(AppSettingsPlugin.kt:45)
        at com.example.appsettings.AppSettingsPlugin.registerWith(Unknown Source:2)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:18)
        at com.mazibook.MainActivity.configureFlutterEngine(MainActivity.java:11)

In GeneratePluginRegistrant.java file I have noticed the following lines which are causing to be crash.
see the following code.

`@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      **com.example.appsettings.AppSettingsPlugin.registerWith(shimPluginRegistry.registrarFor("com.example.appsettings.AppSettingsPlugin"));**
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.connectivity.ConnectivityPlugin());
    flutterEngine.getPlugins().add(new com.tahamalas.custom_switch_button.CustomSwitchButtonPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.deviceinfo.DeviceInfoPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.core.FirebaseCorePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin());
      io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
      notificationsenabled.notifications_enabled.NotificationsEnabledPlugin.registerWith(shimPluginRegistry.registrarFor("notificationsenabled.notifications_enabled.NotificationsEnabledPlugin"));
  }
}`

The problem seems to me is with package name. com.exmple.xxxxx.

Can you please let me know how can we resolve this issue.?

Thank you.
Asif.

**Comment by plinkos** [comment]
Is this still and issue for you?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vishal767** [comment]
+1

**Comment by spencerccf** [comment]
@asifjavaid Are you using Java or Kotlin?  This plugin only works with Kotlin.

**Comment by Yongle-Fu** [comment]
0   libswiftCore.dylib            	       0x19c437990 swift_getObjectType + 40
1   app_settings                  	       0x105ed006c static SwiftAppSettingsPlugin.register(with:) + 108
2   app_settings                  	       0x105ed006c static SwiftAppSettingsPlugin.register(with:) + 108
3   app_settings                  	       0x105ed025c @objc static SwiftAppSettingsPlugin.register(with:) + 56
4   app_settings                  	       0x105ecfd74 +[AppSettingsPlugin registerWithRegistrar:] + 76
5   Easleep                       	       0x102206c40 +[GeneratedPluginRegistrant registerWithRegistry:] + 132
6   Easleep                       	       0x102207654 AppDelegate.application(_:didFinishLaunchingWithOptions:) + 112
