### ISSUE TITLE
i can't open wifi settings in ios

### ISSUE THREAD

**Issue by mohadel92** [spencerccf/app_settings#61]
sorry the readme guide is very short and brief
i couldnt understand how to open wifi  settings and mobile data settings in ios?

**Comment by plinkos** [comment]
Settings on iOS behave very different than Android.  All settings for iOS will open up to the main app settings screen.  Apple does not allow apps to jump into specific individual settings screens but only allows app level/general settings screen. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
