### ISSUE TITLE
Module 'app_settings' not found?

### ISSUE THREAD

**Issue by jimmyrogue** [spencerccf/app_settings#62]
![image](https://user-images.githubusercontent.com/6006189/86073382-32f5b880-bab6-11ea-9073-57c4513c5780.png)

```
fatal error: module 'app_settings' not found
    @import app_settings;
     ~~~~~~~^~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
```

Can u help me?

**Comment by jimmyrogue** [comment]
I solved

**Comment by vishal767** [comment]
What was the error ? I'm facing the same issue

**Comment by jimmyrogue** [comment]
@vishal767 vis 
delete your Podfile in "ios" dir and  run commond "flutter run", flutter will create a new podfile and make sure it looks like below
![image](https://user-images.githubusercontent.com/6006189/86904175-e60f8300-c142-11ea-9e31-a3d643fd964e.png)
