### ISSUE TITLE
fatal error: 'app_settings/app_settings-Swift.h' file not found

### ISSUE THREAD

**Issue by rnayala** [spencerccf/app_settings#66]
When trying to build the iOS app i get the following error:

/development/flutter/.pub-cache/hosted/pub.dartlang.org/app_settings-4.0.2/ios/Classes/AppSettingsPlugin.m:2:9: fatal error: 'app_settings/app_settings-Swift.h' file not found
    #import <app_settings/app_settings-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

I am using app_settings 4.0.2 and have SWIFT 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.3.0

**Comment by plinkos** [comment]
It looks like even though you have Swift 5.2.4 running on your system your Flutter project may have been setup using defaults which uses Objective-C.   This plugin will only work with Flutter projects setup to use Swift using the `-i swift` flag.

**Comment by atefsawaed** [comment]
I've had the same issue and I solved it by adding use_frameworks! to my Runner project in my Podfile.

- target 'Runner' do
    use_frameworks!

**Comment by spencerccf** [comment]
@rnayala please try @atefsawaed solution... should solve your issue.  I'm closing this ticket for now... re-open if you still have an issue.
