### ISSUE TITLE
All options open the current 'app' settings section if there are settings defined. If no current settings are defined for the app the iPhone Settings Screen will be displayed.

### ISSUE THREAD

**Issue by itMcdull** [spencerccf/app_settings#70]
Can I not set the current settings for the application?

**Comment by plinkos** [comment]
What settings are you looking to set for the application?

**Comment by itMcdull** [comment]
What I mean is how to jump to the system settings above ios 10, is there any way, even if it is rejected, it does not matter

**Comment by plinkos** [comment]
There is a way to do that but it's no longer supported by Apple and our plugin will not be able to support that feature.
