### ISSUE TITLE
Location settings page sends me back to Settings page

### ISSUE THREAD

**Issue by utpal-barman** [spencerccf/app_settings#71]
```
final AndroidIntent intent = AndroidIntent(
                        action: 'android.settings.LOCATION_SOURCE_SETTINGS');
intent.launch();
```

I used this to get to the settings page on Android, it works fine, going to settings page, but when I press the back icon (Appbar leading Icon on Location Settings Page), it navigates to the Settings Screen of my phone, but usually, users don't want to see this. I guess, if it can be implemented in a way that clears the stack, and directly navigate me to the app screen.

**Comment by plinkos** [comment]
Going to add this to our list of enhancements and see if there is a way to have the back icon send user back to app.  In most cases this does.  What version of Android are you running?

**Comment by utpal-barman** [comment]
Android 9
