### ISSUE TITLE
Not able to open display settings on iPhone

### ISSUE THREAD

**Issue by Chrisjc28** [spencerccf/app_settings#73]
when using ```AppSettings.openDisplaySettings()``` on a iphone simulator it doesn't open the correct settings page just takes you to the app settings page

**Comment by plinkos** [comment]
We will investigate this feature for iOS.  In doing some initial research this looks like it's possible to adjust some display settings however Apple will most likely not allow you to open the actual Display Settings screen programmatically.  If there is a display setting added to the plugin then those will appear in under the App Settings.

**Comment by spencerccf** [comment]
Which display settings are you looking to use in your app?  I am working on adding the ability to change brightness from 0.1 to 1.0 so you can control screen brightness from within your app.

**Comment by putheakhem** [comment]
@spencerccf  I'm looking for WIFI and Mobile Data Setting.
