### ISSUE TITLE
Problem with IOS (GeneratedPluginRegistrant)

### ISSUE THREAD

**Issue by brasizza** [spencerccf/app_settings#77]
Hi!
My app was fully compiled and i was testing yesterday without any problem.
Today i had to compile another version and now i got this error

GeneratedPluginRegistrant.m:10:9: fatal error: module 'app_settings' not found
    @import app_settings;

i`m using (   app_settings: ^4.0.4) and even with the older version the errors are the same.

can you help me ?

**Comment by plinkos** [comment]
Are you using the new version of Flutter?  Flutter just released this new version.  We will need to upgrade the plug-in with the latest. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brasizza** [comment]
> Are you using the new version of Flutter? Flutter just released this new version. We will need to upgrade the plug-in with the latest.
> 
> Sent with [GitHawk](http://githawk.com)

Just fixed upgrading the base ios version from 10 to 12... what a think!!
thanks!
