### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by zigapovhe** [spencerccf/app_settings#85]
Are there any plans to add null safety support, and if so: when do you think this might happen?

**Comment by plinkos** [comment]
Yes, I’ll get that updated in the next day or so and push up a new version. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zigapovhe** [comment]
Perfect, thanks!

**Comment by plinkos** [comment]
@zigapovhe apologies for the delay... still working on migrating to null safety.

**Comment by zigapovhe** [comment]
No worries. If you need some help, please let me know.
