### ISSUE TITLE
AppSettings.openSecuritySettings() opening security settings but need to open Lock Screen and password settings screen in Android.

### ISSUE THREAD

**Issue by Praveen-Ramalingam** [spencerccf/app_settings#94]
In this case, my device has lock screen and password as settings for security rather the name as security so how to handle this case.

![image-2021-04-05-13-55-05-122](https://user-images.githubusercontent.com/73332872/113856225-9851a500-97be-11eb-9473-c74f3f69dc1d.png)
![image-2021-04-05-13-54-06-937](https://user-images.githubusercontent.com/73332872/113856234-9a1b6880-97be-11eb-892e-8296fe27d899.png)

**Comment by Praveen-Ramalingam** [comment]
@spencerccf Can you please help me on this issue

**Comment by Praveen-Ramalingam** [comment]
Any update on this issue @spencerccf

**Comment by plinkos** [comment]
This will need to be an enhancement to the plugin.  See: https://stackoverflow.com/questions/53778920/android-open-lock-screen-settings-programmatically

**Comment by mustakimpawle** [comment]
Any update on this?

**Comment by plinkos** [comment]
Now available in pub.dev version: 4.1.3
