### ISSUE TITLE
openXyzSettings futures immediately return

### ISSUE THREAD

**Issue by AlexHartford** [spencerccf/app_settings#99]
Hi, I'm wondering if there would be a way to have this code behave as expected:
```dart
onPressed: () async {
    debugPrint('opening settings');
    await AppSettings.openWIFISettings(asAnotherTask: true);
    debugPrint('user came back to app');
},
```

Both of these print immediately. I tried adding an await in the library code but then the function never returns at all, so the second print would never be reached.

**Comment by weihenglim** [comment]
Issue is still present in the latest version (4.1.5), is this the intended behavior?

**Comment by RobertBrunhage** [comment]
This is still happening

**Comment by plinkos** [comment]
Could you paste a code sample of how you are calling AppSettings.openWIFISettings?

**Comment by RobertBrunhage** [comment]
When we call the below code the print happens before you navigate back to the page (right away when the settings page opens)

```dart
await AppSettings.openNotificationSettings();
print('should happen when you are done with settings');
```

**Comment by plinkos** [comment]
New callback functionality has been added.  Please update your onpress button event to call AppSettings this way

onPressed: (() {
                  AppSettings.openWIFISettings(callback: () {
                    print("sample callback function called");
                  });
                }),

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by amedeopro** [comment]
have you solved? @RobertBrunhage

**Comment by RobertBrunhage** [comment]
Haven't tried it in a while, believe we tested with latest version but didn't await until the app was in foreground again, so we handled it with the lifecycle approach (check status during foreground again)

**Comment by amedeopro** [comment]
@RobertBrunhage  I don't think I understood how you solved it, I have the problem that if I do openWiFiSettings() it doesn't wait and I don't get the notification asking me for permission to access the local network in iOS, could you give me some advice on this ?

**Comment by RobertBrunhage** [comment]
@amedeopro use lifecycle events and listen for foreground event, check during that.

**Comment by slice-mohit** [comment]
Still not working. I'm doing this.

```
      await AppSettings.openAppSettings(type: AppSettingsType.notification);

      print('returned from notification settings');
```

The sentence is printed as soon as user enters settings menu. Expected it to be printed after he returns to app from settings.

**Comment by UlrichRaab** [comment]
This issue still exists in 5.0.0

**Comment by RobertBrunhage** [comment]
@slice-mohit I don't `await` to do the action. I use Flutter lifecycle and check when the app comes in the foreground again to check the status.
